### PR TITLE
Add Code4z section

### PR DESCRIPTION
**Pull request by zeibura**
This pull request adds another section to the guide about Code4z (specifically the COBOL Language Support and Zowe Explorer extensions) and includes an overview of all their features and in-depth walkthroughs for working with Zowe Profiles, which are necessary for working with data sets and copybooks on the mainframe.

### CODE REVIEW

**Comment by zeibura** [comment]
This is related to https://github.com/openmainframeproject/cobol-programming-course/issues/51

**Comment by zeibura** [comment]
I'm open to suggestions about restructuring this btw, esp. about whether Zowe Explorer should have its own section

**Comment by MikeBauerCA** [comment]
My recommendation would be to split your contribution into three sections, a chapter on Zowe Explorer, another chapter on Code4z, and a section on installing Code4z in the "Installation of VS Code and extensions" chapter. Below is my recommended structure for "Part 1 - Getting started" after this PR:

1. Why COBOL?
2. VS Code with Zowe Explorer
3. VS Code with Z Open Editor
4. VS Code with Code4z
5. Zowe CLI and Zowe CLI Plug-ins
6. Installation of VS Code and Extensions
    - Zowe Explorer
    - Z Open Editor
    - Code4z
7. Installation of Zowe CLI and Plug-ins

**Comment by zeibura** [comment]
I'm going to rearrange the structure of this as suggested by Mike

**Comment by zeibura** [comment]
- sections have been restructured as suggested by @MikeBauerCA above
- image captions have been added to the Code4z section
- summaries have been added to the Code4z and Zowe Explorer sections
- Code4z installation instructions added to the installing section
- I removed "Zowe extension" from the Z Open Editor section title as I couldn't find a reference to Zowe Explorer in there

The only thing that occurred to me is that it might make more sense to put the installing sections before the introductions, especially since a few of the introductions are basically walkthroughs.

**Comment by zeibura** [comment]
Conflicts resolved - ready for merge.

**Pull request merged**
