### PR TITLE
updating code snippets images

### PR DESCRIPTION
**Pull request by ahmedEid1**
Signed-off-by: ahmedEid1 <ahmedeid6422@gmail.com>

This PR updates images:

107 & 108 in the Data Division chapter,
125-131 in the File Handling chapter,
141-145 in the File Output chapter,
000-002 & 162-163 in the Arithmetic expressions chapter.
to use the syntax highlighting provided by the COBOL Language Support VS Code Extension to perform the update. which would make the content more familiar to those using VS Code to complete the labs.
as @MikeBauerCA mentions here #233 (comment)

### CODE REVIEW

**Comment by ahmedEid1** [comment]
@tanto259
this is the same PR, I kind of broke my Git history, so I recreate the PRs on new branches.

**Comment by ahmedEid1** [comment]
@tanto259 

``` Yay! Just a few things to note:

Typo in image001: TBLANACE-O.
Missing a . at the last line on image002.
Typo in image106: heigher. Also, we may want to check that the chapter number mentioned is correct, and I believe the file name of the FD statement should begins in area B.
Typo in image107: PRINT_REC. Chapter numbering seems wrong when compared to the current list, and I believe the file name of the FD statement should begins in area B.
Typo in image108: fiftheen, postions. Also, the COMPUTE statement is missing, and the column numbering on the third line is off. We may also want to check that the figure number and page is correct.
Typo in image127: Pliot, Oocupation.
Typo in image131: LASTRIC = 'Y', PERFORM WRIYR-RECORD. Also, it will be nice if the arrow can be consistent (either just a arrowed line, or a filled arrow, or a hollow arrow).
Typo in image141: &SYSSUID.DATA, CBL001J.
Typo in image142: decribes, CBL001J. Also, variable name should be plural (i.e. variable names). And I believe the file name of the FD statement should begins in area B.
Typo in image143: strctures. Also, that need to be setup....
Typo in image162: preforms, statment, LIMIT-BALANCE-TOTLA., ADD ACCT-LIMIT TO LIMIT GIVING TLIMIT.. Also, verb assigns the value..., the statements....
Typo in image163: WRITE-TLIMI-TBALANCE.
Also, some nice-to-have improvements, but not really necessary I think...

If in image108, we can standardize the capitalization of COBOL (all caps) and fix the ONLY CONTAINS 13 CHARACTERS to lowercase
If in image127 the lines can be straighter, it will be nice :)
If in image144 PIC 9(02) can be aligned to the rest of the PIC clauses
```

**Comment by ahmedEid1** [comment]
@tanto259 
> image108: We may also want to check that the figure number and page is correct.

it is figure 1 (Part 2 - Learning COBOL 8 Basic COBOL - 8.2.1 What are the coding rules and the reference format?)

should I just remove the page number or replace it with something like 
> Part 2 - Learning COBOL - Basic COBOL - What are the coding rules and the reference format?

image108

**Comment by MikeBauerCA** [comment]
@ahmedEid1 I just noticed in the image above, the first `MOVE` is shown as `Move`

**Comment by tanto259** [comment]
> should I just remove the page number or replace it with something like

I think it should be safe to just remove the `(Figure 1., page 32)` since the image will have a description underneath on the Markdown file...

**Review by MikeBauerCA — APPROVED** [review]
Thank you for making these updates!

**Pull request merged**
