### PR TITLE
Add comments

### PR DESCRIPTION
**Pull request by klausmelcher**
Comments help the novice programmer to understand language concepts and syntax.
Extensive use of comments is also good programming practice for professionals.

### CODE REVIEW

**Comment by klausmelcher** [comment]
@Sudharsana-Srinivasan i don't know how to resolve the issue " This branch has conflicts that must be resolved"

**Comment by binary-sequence** [comment]
Hi @klausmelcher,

I checked out your branch and performed a merge with the master branch of the main repository.
I didn't get any conflict. But, I noticed something strange on this repository that causes a GitHub check to report an "outdated" branch if another pull request was merged. It may be related to the report that your branch has a conflict, even when I didn't encountered any when performing a merge.

Do you know how to do that? It is long to explain. You need to add this repo as another remote repository in addition to your fork repository and `git pull origin master` into your **add-comments** branch.

I could create a PR with your commit and a merge commit.

**Comment by klausmelcher** [comment]
I resolved the conflict, but i'm unable to do the DCO and to merge the pull request

**Comment by binary-sequence** [comment]
Let me try to help here.
Something wrong happened. Some already merged commits were duplicated. It looks like you did a rebase on the wrong branch.

**Comment by binary-sequence** [comment]
Please, find #91

**Comment by klausmelcher** [comment]
@binary-sequence Thank you for your help, but your PR #91 is now outdated and i can' t update it. Mine says "This pull request can be automatically merged by project collaborators" but i can't do DCO

**Comment by binary-sequence** [comment]
@klausmelcher, your are welcome. #91 is merged now, this PR can be closed :)

**Comment by Sudharsana-Srinivasan** [comment]
per @binary-sequence comment, closing this PR

**Pull request closed without merging**
