### PR TITLE
Contribution to Issue #112

### PR DESCRIPTION
**Pull request by klausmelcher**
In order to address issue #112, I made a new CBL0003.cobol program for secton "Program Structure".
To run the new program, I copied old CBL0003J.jcl  to CBL0033J.jcl and changed CBL0003J.jcl to include compilation and link of HELLO.cobol.
The *.md file was also modified to reflect the change from CBL0003J.jcl  to CBL0033J.jcl.
Added new Lab description to section "Program structure"

### CODE REVIEW

**Comment by Sudharsana-Srinivasan** [comment]
Thanks @klausmelcher . @paulnewt is reviewing this contribution.

**Comment by jellypuno** [comment]
Just out of curiosity, Why did you change CBL0003J to compile the HELLO program? Why not just do it in CBL0033J?

**Comment by klausmelcher** [comment]
> 
> 
> Just out of curiosity, Why did you change CBL0003J to compile the HELLO program? Why not just do it in CBL0033J?

@jellypuno Since every COBOL program in the course has its own Job, it makes sense for me that CBL0003J also matches CBL0003.cobol.  Seeing as CBL0003J already existed I moved that one to CBL0033J. However, I could as well leave CBL0003J as it is and use CBL0033J to compile CBL0003.cobol. The new CBL0003.cobol could also be called CBL0033.cobol instead. Please tell me what You think is better.

**Comment by jellypuno** [comment]
> However, I could as well leave CBL0003J as it is and use CBL0033J to compile CBL0003.cobol. The new CBL0003.cobol could also be called CBL0033.cobol instead. Please tell me what You think is better.

I think this would be a good idea so that CBL0003J won't be change. Let's wait for @paulnewt review as well :)

**Pull request merged**
