### PR TITLE
Add initial .gitignore

### PR DESCRIPTION
**Pull request by binary-sequence**
Ignore VIM temporary files and OS configuration metadata

### CODE REVIEW

**Comment by paulnewt** [comment]
@binary-sequence PR is out of date with base branch, could you please update?

**Comment by MikeBauerCA** [comment]
@binary-sequence could you explain further why these files are landing in your local repo?

**Comment by binary-sequence** [comment]
> @binary-sequence could you explain further why these files are landing in your local repo?

- macOS creates `.DS-Store`
- When vim backup setting is enabled, it creates backup files with `filename~`

It is not produced by the course code.
It is a good practice to ignore any file or directory created by the OS or tool used.
People using Windows or another editor could also add more ignore rules.

**Comment by binary-sequence** [comment]
Branch updated

**Pull request merged**
