### PR TITLE
Added Challenge Hacker News

### PR DESCRIPTION
**Pull request by raven300**

### CODE REVIEW

**Comment by raven300** [comment]
> I love it! Instructions are clear for me and there's a reference to DFSort. Thank you for adding this! #moreCOBOLchallenges

Thank you!

**Comment by raven300** [comment]
> Overall, I really like this challenge. One issue with promoting this challenge on our available system is storage. Currently, all participants would be allocating relatively large sequential datasets to store the large CSV file. Instead, could we have an admin create this dataset in a single location and have all participants leverage it? This would mean that participants would essentially skip the first three steps.

I will arrange for this and make changes. Thank you.

**Comment by jellypuno** [comment]
@raven300 I am not sure what happened to the PR. There are 328 files changed and I wanted to try out the challenge but I can't seem to find it in the *.md file 😞

**Comment by raven300** [comment]
> @raven300 I am not sure what happened to the PR. There are 328 files changed and I wanted to try out the challenge but I can't seem to find it in the *.md file 😞

@jellypuno, Sorry about that. I had issues with DCO signoff. I am working on it and hope you can try it out soon!

**Comment by jellypuno** [comment]
> > @raven300 I am not sure what happened to the PR. There are 328 files changed and I wanted to try out the challenge but I can't seem to find it in the *.md file 😞
> 
> @jellypuno, Sorry about that. I had issues with DCO signoff. I am working on it and hope you can try it out soon!

Ah I see. Now, I understand. 😊

**Comment by raven300** [comment]
Replaced by PR 164

**Pull request closed without merging**
