### PR TITLE
Adding Source Modules for COBOL Challenges: Debugging

### PR DESCRIPTION
**Pull request by jellypuno**

### CODE REVIEW

**Comment by zeibura** [comment]
Looks fine, have created #139 for the instructions and pics.

**Comment by zeibura** [comment]
@jellypuno what's the difference between the two programs, CBL0106 and CBL0106C? The instructions I provided only refer to the first one.

**Comment by jellypuno** [comment]
@zeibura CBL0106 is the program that needs debugging. CBL0106C is the fixed version in case the students are stuck and they need help.

**Comment by MikeBauerCA** [comment]
I requested a small change on #139 but see no harm in merging this PR first.

**Pull request merged**
