### PR TITLE
Add comments to CBL0006 and CBL0007

### PR DESCRIPTION
**Pull request by klausmelcher**
Since the Chapter 11.2.3 Conditional names isn't covered in the Labs, i changed the program in a way that the logic is different, but the task and results are the same. I also left the extra dot in the code, so you still have to search the error and correct it.

### CODE REVIEW

**Comment by jellypuno** [comment]
@klausmelcher Thanks for adding this! Do you think the comments can be added in the *.md file?
@MikeBauerCA What do you think?

**Comment by klausmelcher** [comment]
> @klausmelcher Thanks for adding this! Do you think the comments can be added in the *.md file?
> @MikeBauerCA What do you think?
@jellypuno 
I don't know how to obtain the same Syntax highlighting colors as used in the images of the *.md file

**Comment by jellypuno** [comment]
> @jellypuno
I don't know how to obtain the same Syntax highlighting colors as used in the images of the *.md file

You can install [COBOL Bitlang](https://marketplace.visualstudio.com/items?itemName=bitlang.cobol) in your VSCode extension

**Comment by klausmelcher** [comment]
@jellypuno I made an update to my pull request. I did not succeed in matching the colors exactly. If it is good enough, I can add further figures in my next pull request.

**Comment by MikeBauerCA** [comment]
@klausmelcher I see you have added an image in this PR but do not reference it in the course. Where would you like to add the image?

**Comment by klausmelcher** [comment]
> @klausmelcher I see you have added an image in this PR but do not reference it in the course. Where would you like to add the image?

@MikeBauerCA The reference is in line 2895 of the COBOL Programming Course #1 - Getting Started.md file. I would like to replace the image which is already referenced with a new one with comments, as suggested by @jellypuno.

**Pull request merged**
