### PR TITLE
updating code snippets with VS-Code versions

### PR DESCRIPTION
**Pull request by ahmedEid1**
Signed-off-by: ahmedEid1 <ahmedeid6422@gmail.com>

This PR updates images:
- 107 & 108 in the Data Division chapter,
- 125-131 in the File Handling chapter, 
- 141-145 in the File Output chapter, 
- 000-002 & 162-163 in the Arithmetic expressions chapter.
 
to use the syntax highlighting provided by the COBOL Language Support VS Code Extension to perform the update. which would make the content more familiar to those using VS Code to complete the labs.
as @MikeBauerCA mentions here https://github.com/openmainframeproject/cobol-programming-course/pull/233#issuecomment-882570047

### CODE REVIEW

**Review by tanto259 — COMMENTED** [review]
Yay! Just a few things to note:
- Typo in image001: `TBLANACE-O`.
- Missing a `.` at the last line on image002.
- Typo in image106: `heigher`. Also, we may want to check that the chapter number mentioned is correct, and I believe the file name of the FD statement should begins in area B.
- Typo in image107: `PRINT_REC`. Chapter numbering seems wrong when compared to the current list, and I believe the file name of the FD statement should begins in area B.
- Typo in image108: `fiftheen`, `postions`. Also, the COMPUTE statement is missing, and the column numbering on the third line is off. We may also want to check that the figure number and page is correct.
- Typo in image127: `Pliot`, `Oocupation`.
- Typo in image131: `LASTRIC = 'Y'`, `PERFORM WRIYR-RECORD`. Also, it will be nice if the arrow can be consistent (either just a arrowed line, or a filled arrow, or a hollow arrow).
- Typo in image141: `&SYSSUID.DATA`, `CBL001J`.
- Typo in image142: `decribes`, `CBL001J`. Also, `variable name` should be plural (i.e. `variable names`). And I believe the file name of the FD statement should begins in area B.
- Typo in image143: `strctures`. Also, `that need to be setup...`.
- Typo in image162: `preforms`, `statment`, `LIMIT-BALANCE-TOTLA.`, `ADD ACCT-LIMIT TO LIMIT GIVING TLIMIT.`. Also, `verb assigns the value...`, `the statements...`.
- Typo in image163: `WRITE-TLIMI-TBALANCE`.

Also, some nice-to-have improvements, but not really necessary I think...

- If in image108, we can standardize the capitalization of `COBOL` (all caps) and fix the `ONLY CONTAINS 13 CHARACTERS` to lowercase
- If in image127 the lines can be straighter, it will be nice :)
- If in image144 `PIC 9(02)` can be aligned to the rest of the PIC clauses

**Comment by ahmedEid1** [comment]
> * and I believe the file name of the FD statement should begin in area B.
I think `FD` is in the right place can you explain more?

**Comment by tanto259** [comment]
> I think `FD` is in the right place can you explain more?

I'm not really sure if this is required or not. But, I'm referring to the alignment of the names.

image

**Comment by ahmedEid1** [comment]
> * If in image108, we can standardize the capitalization of `COBOL` (all caps)

I think all `COBOL` are all caps?
image108

**Comment by tanto259** [comment]
> > * If in image108, we can standardize the capitalization of `COBOL` (all caps)
> 
> I think all `COBOL` are all caps?
> image108

The one next to `MOVE statements` have a lowercase `l` I think...

**Comment by ahmedEid1** [comment]
> > > * If in image108, we can standardize the capitalization of `COBOL` (all caps)
> > 
> > 
> > I think all `COBOL` are all caps?
> > image108
> 
> The one next to `MOVE statements` have a lowercase `l` I think...


Oh, I really need to wear glasses 😢 🤣 
Thanks, Hartanto

**Pull request closed without merging**
